In [ ]:
# Data Analytics I
# Create a Linear Regression Model using Python/R to predict home prices using Boston Housing 
# Dataset (https://www.kaggle.com/c/boston-housing). The Boston Housing dataset contains 
# information about various houses in Boston through different parameters. There are 506 samples 
# and 14 feature variables in this dataset.

In [102]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

In [71]:
df=pd.read_csv('HousingData.csv')

In [72]:
df.dropna()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,0.00,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,0.0,2.5050,1,273,21.0,396.90,7.88,11.9

In [73]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,0.00,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,0.0,2.5050,1,273,21.0,396.90,7.88,11.9

In [74]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [75]:
x=df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', ]]
y=df['MEDV']

In [76]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,0.00
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,0.0,2.5050,1,273,21.0,396.90,7.88

In [77]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [93]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [94]:
df.dropna()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,0.00,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,0.00,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,0.0,2.5050,1,273,21.0,396.90,7.88,11.9

In [95]:
model=LinearRegression()

In [96]:
model.fit(x_train,y_train)

LinearRegression()

In [97]:
y_pred =model.predict(x_test)

In [98]:
y_pred

array([30.72001335, 36.0608721 , 14.59622533, 24.78451471, 18.16214607,
       22.82106425, 19.88876436, 14.7585557 , 21.70040393, 20.5653581 ,
       25.15612955, 18.76085589, -5.88859904, 21.71785074, 18.60381008,
       29.93644257, 19.34514194,  6.00632729, 40.73433331, 16.87718256,
       29.67136668, 29.91787082, 11.76451079, 27.33072305, 16.8118639 ,
       14.74185717, 25.94301656, 14.04297638, 22.7373344 , 19.1562395 ,
       22.28715444, 24.71392929, 24.90576713, 15.76412037, 16.40100411,
       16.36115141, 30.58989689, 19.79845767, 24.36323282, 27.60112708,
       14.60254718, 31.67758014, 42.69434382, 17.67279075, 27.19141191,
       15.9923441 , 13.92895626, 25.98102921, 19.55365193, 29.70075315,
       20.98472222, 35.08463147, 16.21532945, 25.75232485, 39.40763671,
       21.73437902, 17.98882879, 32.14534653, 25.13629191, 13.22084182,
       22.57201602, 30.44309883, 31.33488649, 15.83322631, 20.22364748,
       17.35638585, 19.78394461, 25.78591775, 30.41563599, 10.97798633,
       21.00630499, 25.9792416 , 10.81051047, 13.63232869, 23.6104523 ,
        6.24495657, 21.13879516, 41.4558362 , 18.43304706,  9.16986898,
       20.81221024, 13.29537132, 21.07945926,  9.11155823, 22.49182013,
       32.01205521, 19.15644112, 25.08110916, 28.23733925, 19.34700299,
       25.76956056,  5.44588267, 18.93072788, 15.28133944,  9.49559985,
       19.43433281, 22.83062101,  0.11495478, 12.92129289, 15.71027068,
       22.66651195, 24.18933621, 10.57390807, 18.75963606, 22.28556112,
       14.17805908, 17.81497513, 25.13370461, 20.47409598, 23.80116228,
        7.86947513, 20.97720743, 21.38976139, 27.3831197 , 31.95960048,
       13.86448055, 35.24178084, 12.70756446, 20.69695336, 27.5937992 ,
       14.91391332, 24.4614033 ,  2.78192874, 23.22511052, 25.60589952,
       22.42008918, 24.46928502])

In [99]:
# Returns the mean accuracy on the given test data and labels.
model.score(x_train,y_train)

0.7342386356345362

In [101]:
model.score(x_test,y_test)

0.6714313925008552

In [103]:
np.sqrt(mean_squared_error(y_test,y_pred))

4.796740672334888